### ISSUE TITLE
Insecure File Management in composer plugin

### ISSUE THREAD

**Issue by kpicaza** [antidot-framework/installer#4]
:warning: We detected security issues in this pull request:

<details>
<summary>Insecure File Management (9)</summary>

https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/Template/Micro/FileStructure.php#L47  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/Template/Micro/FileStructure.php#L35  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/Template/ComposerJson.php#L41  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/Template/Micro/FileStructure.php#L53  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/ApplicationType/MicroAppInstaller.php#L58  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/ApplicationType/MicroAppInstaller.php#L57  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/Template/ComposerJson.php#L71  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/Template/Micro/FileStructure.php#L39  
https://github.com/antidot-framework/installer/blob/e495073e54a878f4272d0d08467f9329914f5f8c/src/ApplicationType/MicroAppInstaller.php#L48  

More info on how to fix Insecure File Management in [PHP](https://docs.guardrails.io/docs/en/vulnerabilities/php/Insecure_file_management.html?utm_source=ghpr).</details>

---
👉 Go to the [dashboard](https://dashboard.guardrails.io/default/gh/antidot-framework/installer/e495073e54a878f4272d0d08467f9329914f5f8c?type=pull) for detailed results.

📥 Happy? Share your [feedback](https://guardrails.typeform.com/to/BCgBkB) with us.

_Originally posted by @guardrails in https://github.com/antidot-framework/installer/pull/3#issuecomment-678761615_

**Comment by streichsbaer** [comment]
Hi @kpicaza, I have taken a look at these issues, and in the context of an installation, there is not much that can be done here.

Also, given that this is a one time-activity, and the package is deleted afterwards, this further reduces the risk dramatically.

We are just about to launch the ability to mark these findings as "Won't fix" (amongst other states) in the dashboard, this way they won't keep showing up.

**Comment by kpicaza** [comment]
Hi @streichsbaer, Thanks for the response, let us know when the new feature is available to restore @guardrails security checks.
